name: Automated tests

on:
  push:
    branches: [main, master]  # ← Добавьте триггер для веток

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ← Обновите до v4

      - name: Setup Python
        uses: actions/setup-python@v5  # ← Исправлено: setup-python вместо setup-Python и v5
        with:
          python-version: "3.13"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d'.' -f1)
          wget -O chromedriver.zip "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR_VERSION"
          wget -O chromedriver.zip "https://chromedriver.storage.googleapis.com/$(cat chromedriver.zip)/chromedriver_linux64.zip"
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Install Allure Commandline
        run: |
          sudo apt-get update
          sudo apt-get install -y allure
          allure --version

      - name: Run tests with Allure
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Upload Allure report
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: test
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4